### ISSUE TITLE
When drawing overlapping rectangles, the erase tool doesn't correctly erase a segment

### ISSUE THREAD

**Issue by bertyhell** [bertyhell/openwebcad#6]
![image](https://github.com/user-attachments/assets/c5f6ff96-a73d-42c0-ace0-70e90360e36d)

**Comment by P-yiush07** [comment]
Can i Fix this ? @bertyhell 
I want to do some open source contributions. Please give me a chance. 
Thanks

**Comment by bertyhell** [comment]
sure give it a go.

the bug is probably in one of these locations:
https://github.com/bertyhell/openwebcad/blob/master/src/tools/eraser-tool.ts#L125

https://github.com/bertyhell/openwebcad/blob/master/src/tools/eraser-tool.helpers.ts#L29

**Comment by P-yiush07** [comment]
@bertyhell Please leave this bug on me, I'll solve it. 
thanks.

**Comment by P-yiush07** [comment]
@bertyhell are you there ?

**Comment by bertyhell** [comment]
@P-yiush07 yes, ill check it this weekend

**Comment by bertyhell** [comment]
merged: https://github.com/bertyhell/openwebcad/pull/7
