### ISSUE TITLE
When erasing part of a circle, the whole circle is erased

### ISSUE THREAD

**Issue by bertyhell** [bertyhell/openwebcad#8]
* Draw a circle
* Draw a rectangle that partly overlaps
* Switch to the erase tool
* Click the circle
![image](https://github.com/user-attachments/assets/32be6c5b-aa8a-4f14-a702-52fef0435f80)

current behavior: The whole circle is deleted
![image](https://github.com/user-attachments/assets/da48b139-5451-4233-8b92-05240c46f907)

expected behavior: Only a segment of the circle should be deleted until the nearest 2 intersection points
![image](https://github.com/user-attachments/assets/e464556e-b788-4830-b456-16f0ff4f265f)

**Comment by P-yiush07** [comment]
@bertyhell Assign me, i will solve this

**Comment by P-yiush07** [comment]
Check the PR, I fixed this issue. #9

**Comment by bertyhell** [comment]
thx is indeed fixed, thx
